In [7]:
#using matplotlib mode, it chooses a suitable backend
%matplotlib

Using matplotlib backend: TkAgg


In [9]:
import csv
import numpy as np
import matplotlib.pyplot as plt

datadict = {}
with open('data_1.csv') as csvfile:
	data = csv.reader(csvfile, delimiter = ',')
	for row in data:
		datadict[row[0]] = row[1]

#Creating a matrix of each type to further compute
matrix_y = []
matrix_x = []
for i in datadict:
	try:
		matrix_y.append(float(datadict[i]))
		matrix_x.append([float(i)*float(i), float(i), 1])
	except ValueError:
		#The value found is not a float
		continue

y = np.array(matrix_y)
x = np.array(matrix_x)

xt = np.transpose(x) mnnn
#print(YT)
one = np.linalg.inv(np.matmul(xt, x))
two = np.matmul(xt, y)

B = np.matmul(one, two)

yi = []
xcoords = []
for xi in x:
	yi.append(xi[0]*B[0] + xi[1]*B[1] + xi[2]*B[2])
	xcoords.append(xi[1])

plt.plot(xcoords, matrix_y, 'bo')
plt.plot(xcoords, yi, 'ro')
plt.show()

In [25]:
def check_inlier(a,b,c,xi,yi,t):
    
    distance = yi -(a*(xi**2)) - (b*xi) - c
    
    if abs(distance) <= t:
        return 1
    
    else:
        return 0


    

In [31]:
check_inlier(1,2,2.7,0,0,3)


1

In [5]:
import numpy as np 
import math
from numpy import linalg as LA

# First entry in list set as None for more intuitive indexing
x = [None, 5, 150, 150, 5]
y = [None, 5, 5, 150, 150]
xp = [None, 100, 200, 220, 100]
yp = [None, 100, 80, 80, 200]

A = np.array([[-x[1], -y[1], -1, 0, 0, 0, x[1]*xp[1], y[1]*xp[1], xp[1]], 
	[0, 0, 0, -x[1], -y[1], -1, x[1]*yp[1], y[1]*yp[1], yp[1]], 
	[-x[2], -y[2], -1, 0, 0, 0, x[2]*xp[2], y[2]*xp[2], xp[2]], 
	[0, 0, 0, -x[2], -y[2], -1, x[2]*yp[2], y[2]*yp[2], yp[2]], 
	[-x[3], -y[3], -1, 0, 0, 0, x[3]*xp[3], y[3]*xp[3], xp[3]], 
	[0, 0, 0, -x[3], -y[3], -1, x[3]*yp[3], y[3]*yp[3], yp[3]], 
	[-x[4], -y[4], -1, 0, 0, 0, x[4]*xp[4], y[4]*xp[4], xp[4]], 
	[0, 0, 0, -x[4], -y[4], -1, x[4]*yp[4], y[4]*yp[4], yp[4]]])



In [2]:

A_transpose = np.transpose(A)

# intermediate_matrix = c_transpose * c
# intermediate_matrix = np.multiply(c_transpose,c)   #does the dot product
intermediate_matrix = np.matmul(A_transpose,A)

# print(f'C transpose:\n {c_transpose}')

# print(f'Intermediate matrix:\n {intermediate_matrix}')

# eigen_value_matrix = np.diag((1, 2, 3))
# print(diagonal_test)


In [8]:

w, v = LA.eig(intermediate_matrix)
print(w) #Eigen values
print(v) #Eigen vector matrix





[ 3.62583363e+09  1.01280011e+09  6.80651927e+04  3.46776193e+04
  2.12012335e+04  3.70648899e+03  1.52001454e+01  6.56490976e-01
 -4.76010921e-10]
[[ 2.84043894e-03  3.14430147e-03 -2.46384735e-01 -1.58554932e-01
  -1.75245114e-01  1.76705635e-01  9.13738625e-01 -1.20261073e-01
   5.31056350e-02]
 [ 2.42121739e-03 -1.28321626e-03 -3.77000733e-01  1.76600215e-01
   6.89508147e-01  5.90273326e-01 -5.29344506e-02 -2.23230964e-03
  -4.91718844e-03]
 [ 2.20891154e-05  1.13495064e-05 -2.37217168e-03 -3.65660431e-03
   5.19584361e-03  7.52000216e-03  6.59901592e-02  7.85970680e-01
   6.14648552e-01]
 [ 1.09109680e-03  1.17416448e-03  6.61240940e-01  3.41172744e-01
   5.01749740e-01 -2.32499365e-01  3.72052359e-01 -4.25903575e-02
   1.77018784e-02]
 [ 1.63479471e-03 -2.90636016e-03  5.74279813e-01 -7.10405325e-02
  -3.14549320e-01  7.49883366e-01 -6.19835401e-02  4.58785873e-03
  -3.93375075e-03]
 [ 1.33908907e-05 -1.14077892e-05  5.80190908e-03 -2.15181510e-03
   2.88147957e-03 -5.73504703e-

In [14]:
V_eigen_vector_matrix = v
V_transpose = np.transpose(V_eigen_vector_matrix)

eigen_square_root = []
print(abs(w[8]))

4.760109207240793e-10


In [15]:
for i in range(0,len(w)):
	eigen_square_root.append(math.sqrt(abs(w[i])))

# print(eigen_square_root)

Sigma_eigen_value_matrix = np.diag(eigen_square_root)

# print(Sigma_eigen_value_matrix)
# print(math.sqrt(4)) 

Sigma_inverse = np.linalg.inv(Sigma_eigen_value_matrix)

U_matrix = np.matmul(A, np.matmul(V_eigen_vector_matrix,Sigma_inverse))




In [18]:
print('SVD decomposition of C is:\n U: \n' {U_matrix})


SyntaxError: invalid syntax (<ipython-input-18-5d3bed8938c7>, line 1)

In [ ]:
print('Sigma :\n {Sigma_eigen_value_matrix}')
print('V transpose :\n {V_transpose}')

SVD_check = np.matmul(U_matrix, np.matmul(Sigma_eigen_value_matrix, V_transpose))
print(SVD_check)

In [37]:
def matrix_round_off(matrix):
    for i in range(0,np.size(matrix,0)):
        for j in range(0,np.size(matrix,1)):
            matrix[i][j] = round(matrix[i][j],3)
            #print(round(matrix[i][j],2))
    return matrix

In [38]:
matrix_1 = np.array([[-1.2345,-4.6543],[-2.34556,-4.67565]])
print(matrix_1)

[[-1.2345  -4.6543 ]
 [-2.34556 -4.67565]]


In [39]:
matrix_round_off(matrix_1)

array([[-1.234, -4.654],
       [-2.346, -4.676]])

In [40]:
print(V_eigen_vector_matrix[:,8])


[ 5.31056350e-02 -4.91718844e-03  6.14648552e-01  1.77018784e-02
 -3.93375075e-03  7.86750146e-01  2.36025045e-04 -4.91718843e-05
  7.62164205e-03]


In [26]:
arr = np.array([[1], [2], [3],[4], [5], [6],[7], [8], [9]])
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [28]:
reshaped_arr = np.reshape(arr, (3,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np 
import math
from numpy import linalg as LA

# First entry in list set as None for more intuitive indexing
x = [None, 5, 150, 150, 5]
y = [None, 5, 5, 150, 150]
xp = [None, 100, 200, 220, 100]
yp = [None, 100, 80, 80, 200]

A = np.array([[-x[1], -y[1], -1, 0, 0, 0, x[1]*xp[1], y[1]*xp[1], xp[1]], 
	[0, 0, 0, -x[1], -y[1], -1, x[1]*yp[1], y[1]*yp[1], yp[1]], 
	[-x[2], -y[2], -1, 0, 0, 0, x[2]*xp[2], y[2]*xp[2], xp[2]], 
	[0, 0, 0, -x[2], -y[2], -1, x[2]*yp[2], y[2]*yp[2], yp[2]], 
	[-x[3], -y[3], -1, 0, 0, 0, x[3]*xp[3], y[3]*xp[3], xp[3]], 
	[0, 0, 0, -x[3], -y[3], -1, x[3]*yp[3], y[3]*yp[3], yp[3]], 
	[-x[4], -y[4], -1, 0, 0, 0, x[4]*xp[4], y[4]*xp[4], xp[4]], 
	[0, 0, 0, -x[4], -y[4], -1, x[4]*yp[4], y[4]*yp[4], yp[4]]])

print(A)

A_transpose = np.transpose(A)

# intermediate_matrix = c_transpose * c
# intermediate_matrix = np.multiply(c_transpose,c)   #does the dot product
intermediate_matrix = np.matmul(A_transpose,A)

# print(f'C transpose:\n {c_transpose}')

# print(f'Intermediate matrix:\n {intermediate_matrix}')

# eigen_value_matrix = np.diag((1, 2, 3))
# print(diagonal_test)

w, v = LA.eig(intermediate_matrix)
# print(w) #Eigen values
# print(v) #Eigen vector matrix

V_eigen_vector_matrix = v
V_transpose = np.transpose(V_eigen_vector_matrix)

eigen_square_root = []
# print(w[1])

for i in range(0,len(w)):
	eigen_square_root.append(math.sqrt(abs(w[i])))

# print(eigen_square_root)

Sigma_eigen_value_matrix = np.diag(eigen_square_root)

# print(Sigma_eigen_value_matrix)
# print(math.sqrt(4)) 

Sigma_inverse = np.linalg.inv(Sigma_eigen_value_matrix)

U_matrix = np.matmul(A, np.matmul(V_eigen_vector_matrix,Sigma_inverse))

print(f'SVD decomposition of C is:\nU: \n {U_matrix}')	
print(f'Sigma :\n {Sigma_eigen_value_matrix}')	
print(f'V transpose :\n {V_transpose}')

SVD_check = np.matmul(U_matrix, np.matmul(Sigma_eigen_value_matrix, V_transpose))
print(f'SVD check matrix:\n {SVD_check}')

# custom function to round off a matrix to five decimal places
def matrix_round_off(matrix):
    for i in range(0,np.size(matrix,0)):
        for j in range(0,np.size(matrix,1)):
            matrix[i][j] = round(matrix[i][j],5)
            #print(round(matrix[i][j],2))
    return matrix

print(matrix_round_off(SVD_check))			

print('Homography matrix is:- \n')
last_column_v = V_eigen_vector_matrix[:,8]

homography_matrix = np.reshape(last_column_v, (3,3))
print(homography_matrix)   #full precision
# print(matrix_round_off(homography_matrix))  #uncomment for rounding off 